version: '3'
services:
  user-db:
    image: mysql:8.0.17
    volumes:
      - user-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_DB
      TZ: Asia/Tokyo
    ports:
      - "4306:3306"
  user:
    build:
      context: .
      dockerfile: Dockerfile.fresh
    volumes:
      - ./src/.:/app
    depends_on:
      - user-db
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - "50051:50051"
      
volumes:
  user-data:
    driver: local