version: '3.4'
services:
  profile-db:
    image: mysql:8.0
    volumes:
      - profile-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profile_DB
      TZ: Asia/Tokyo
    ports:
      - "6306:3306"

  profile:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    depends_on:
      - profile-db
    tty: true
    environment:
      TZ: Asia/Tokyo

volumes:
  profile-data:

networks:
  default:
    external:
      name: fishapp-net
