version: '3'
services:
  profile-db:
    image: mysql:8.0.17
    volumes:
      - profile-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profile_DB
      TZ: Asia/Tokyo
    ports:
      - "6306:3306"

  profile:
    build:
      context: .
      dockerfile: Dockerfile.fresh
    volumes:
      - ./src/.:/app
    depends_on:
      - profile-db
    tty: true
    environment:
      TZ: Asia/Tokyo

volumes:
  profile-data:
    driver: local
networks:
  default:
    external:
      name: api-gateway_default
