// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sex int32

const (
	Sex_SEX_UNSPECIFIED Sex = 0
	Sex_MALE            Sex = 1
	Sex_FEMALE          Sex = 2
)

var Sex_name = map[int32]string{
	0: "SEX_UNSPECIFIED",
	1: "MALE",
	2: "FEMALE",
}

var Sex_value = map[string]int32{
	"SEX_UNSPECIFIED": 0,
	"MALE":            1,
	"FEMALE":          2,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}

func (Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

type Profile struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string               `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Sex                  Sex                  `protobuf:"varint,4,opt,name=sex,proto3,enum=profile_grpc.Sex" json:"sex,omitempty"`
	UserId               int64                `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Profile) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_SEX_UNSPECIFIED
}

func (m *Profile) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Profile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Profile) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetProfileReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileReq) Reset()         { *m = GetProfileReq{} }
func (m *GetProfileReq) String() string { return proto.CompactTextString(m) }
func (*GetProfileReq) ProtoMessage()    {}
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *GetProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileReq.Unmarshal(m, b)
}
func (m *GetProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileReq.Marshal(b, m, deterministic)
}
func (m *GetProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileReq.Merge(m, src)
}
func (m *GetProfileReq) XXX_Size() int {
	return xxx_messageInfo_GetProfileReq.Size(m)
}
func (m *GetProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileReq proto.InternalMessageInfo

func (m *GetProfileReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateProfileReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Sex                  Sex      `protobuf:"varint,3,opt,name=sex,proto3,enum=profile_grpc.Sex" json:"sex,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileReq) Reset()         { *m = CreateProfileReq{} }
func (m *CreateProfileReq) String() string { return proto.CompactTextString(m) }
func (*CreateProfileReq) ProtoMessage()    {}
func (*CreateProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *CreateProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileReq.Unmarshal(m, b)
}
func (m *CreateProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileReq.Marshal(b, m, deterministic)
}
func (m *CreateProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileReq.Merge(m, src)
}
func (m *CreateProfileReq) XXX_Size() int {
	return xxx_messageInfo_CreateProfileReq.Size(m)
}
func (m *CreateProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileReq proto.InternalMessageInfo

func (m *CreateProfileReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProfileReq) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateProfileReq) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_SEX_UNSPECIFIED
}

func (m *CreateProfileReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateProfileReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileReq) Reset()         { *m = UpdateProfileReq{} }
func (m *UpdateProfileReq) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileReq) ProtoMessage()    {}
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *UpdateProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileReq.Unmarshal(m, b)
}
func (m *UpdateProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileReq.Marshal(b, m, deterministic)
}
func (m *UpdateProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileReq.Merge(m, src)
}
func (m *UpdateProfileReq) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileReq.Size(m)
}
func (m *UpdateProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileReq proto.InternalMessageInfo

func (m *UpdateProfileReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProfileReq) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateProfileReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteProfileReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProfileReq) Reset()         { *m = DeleteProfileReq{} }
func (m *DeleteProfileReq) String() string { return proto.CompactTextString(m) }
func (*DeleteProfileReq) ProtoMessage()    {}
func (*DeleteProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *DeleteProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProfileReq.Unmarshal(m, b)
}
func (m *DeleteProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProfileReq.Marshal(b, m, deterministic)
}
func (m *DeleteProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProfileReq.Merge(m, src)
}
func (m *DeleteProfileReq) XXX_Size() int {
	return xxx_messageInfo_DeleteProfileReq.Size(m)
}
func (m *DeleteProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProfileReq proto.InternalMessageInfo

func (m *DeleteProfileReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("profile_grpc.Sex", Sex_name, Sex_value)
	proto.RegisterType((*Profile)(nil), "profile_grpc.Profile")
	proto.RegisterType((*GetProfileReq)(nil), "profile_grpc.GetProfileReq")
	proto.RegisterType((*CreateProfileReq)(nil), "profile_grpc.CreateProfileReq")
	proto.RegisterType((*UpdateProfileReq)(nil), "profile_grpc.UpdateProfileReq")
	proto.RegisterType((*DeleteProfileReq)(nil), "profile_grpc.DeleteProfileReq")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x8e, 0x93, 0x5e,
	0x14, 0xc7, 0xe7, 0x02, 0x85, 0x5f, 0xcf, 0x6f, 0xa8, 0x78, 0x8d, 0x0e, 0x61, 0xa2, 0x12, 0xdc,
	0x10, 0x17, 0x54, 0xab, 0x2e, 0xdc, 0x59, 0x66, 0xe8, 0xa4, 0x89, 0x9a, 0x09, 0x38, 0x89, 0xbb,
	0x86, 0x29, 0x67, 0x1a, 0x92, 0xb6, 0x20, 0xbd, 0x9d, 0xd4, 0xad, 0xc6, 0xa7, 0xf1, 0x0d, 0x7c,
	0x22, 0x9f, 0xa1, 0x2b, 0xc3, 0x05, 0x32, 0xbd, 0x38, 0xcd, 0xac, 0x5c, 0x71, 0x0f, 0xe7, 0xdf,
	0xf7, 0x7c, 0xce, 0x05, 0xd0, 0xf3, 0x22, 0xbb, 0x4a, 0xe7, 0xe8, 0xe5, 0x45, 0xc6, 0x32, 0x7a,
	0x58, 0x9b, 0x93, 0x59, 0x91, 0x4f, 0xad, 0xa3, 0xeb, 0x78, 0x9e, 0x26, 0x31, 0xc3, 0x7e, 0x73,
	0xa8, 0xc2, 0xac, 0xa7, 0xb3, 0x2c, 0x9b, 0xcd, 0xb1, 0xcf, 0xad, 0xcb, 0xf5, 0x55, 0x9f, 0xa5,
	0x0b, 0x5c, 0xb1, 0x78, 0x91, 0xd7, 0x01, 0xc7, 0xed, 0x00, 0x5c, 0xe4, 0xec, 0x6b, 0xe5, 0x74,
	0x7e, 0x48, 0xa0, 0x9d, 0x57, 0x7d, 0x68, 0x0f, 0xa4, 0x34, 0x31, 0x89, 0x4d, 0x5c, 0x39, 0x94,
	0xd2, 0x84, 0x52, 0x50, 0x96, 0xf1, 0x02, 0x4d, 0xc9, 0x26, 0x6e, 0x37, 0xe4, 0x67, 0xea, 0xc0,
	0x61, 0xba, 0x64, 0x45, 0x96, 0xac, 0xa7, 0x2c, 0xcd, 0x96, 0xa6, 0xcc, 0x7d, 0xc2, 0x3b, 0xfa,
	0x0c, 0xe4, 0x15, 0x6e, 0x4c, 0xc5, 0x26, 0x6e, 0x6f, 0x70, 0xdf, 0xdb, 0x1d, 0xc3, 0x8b, 0x70,
	0x13, 0x96, 0x5e, 0x7a, 0x04, 0xda, 0x7a, 0x85, 0xc5, 0x24, 0x4d, 0xcc, 0x0e, 0xef, 0xa8, 0x96,
	0xe6, 0x38, 0xa1, 0x6f, 0x01, 0xa6, 0x05, 0xc6, 0x0c, 0x93, 0x49, 0xcc, 0x4c, 0xd5, 0x26, 0xee,
	0xff, 0x03, 0xcb, 0xab, 0x66, 0xf0, 0x9a, 0x19, 0xbc, 0x4f, 0xcd, 0x90, 0x61, 0xb7, 0x8e, 0x1e,
	0xb2, 0x32, 0x75, 0x9d, 0x27, 0x4d, 0xaa, 0x76, 0x77, 0x6a, 0x1d, 0x3d, 0x64, 0xce, 0x4b, 0xd0,
	0xcf, 0x90, 0xd5, 0x24, 0x42, 0xfc, 0x42, 0xed, 0x1b, 0x7d, 0x9c, 0x88, 0xaf, 0x6d, 0x7d, 0xc5,
	0x91, 0x5c, 0xd2, 0x08, 0x75, 0x7e, 0x11, 0x30, 0x4e, 0x78, 0xef, 0x9d, 0xb4, 0xc7, 0x35, 0xb3,
	0x32, 0xa7, 0xeb, 0x77, 0xb7, 0xbe, 0x5a, 0x28, 0x06, 0x31, 0xa1, 0xc6, 0xe7, 0xb5, 0xf0, 0x71,
	0xb4, 0x3e, 0x6c, 0x7d, 0xad, 0xe8, 0x18, 0xc4, 0xfc, 0xad, 0xb5, 0x50, 0xbe, 0xa9, 0x50, 0xca,
	0x7b, 0x50, 0xfa, 0xc6, 0xd6, 0xef, 0x7c, 0x23, 0x92, 0x7d, 0x50, 0x3d, 0x0d, 0x52, 0xc1, 0xdd,
	0x11, 0xaf, 0xdc, 0x2e, 0xfe, 0x3b, 0x01, 0xe3, 0x82, 0x4f, 0xff, 0xef, 0xc4, 0xef, 0xa8, 0x90,
	0x6f, 0x57, 0xf1, 0x1a, 0x8c, 0x53, 0x9c, 0xa3, 0x20, 0xe2, 0x4e, 0xf0, 0xcf, 0x5f, 0x80, 0x1c,
	0xe1, 0x86, 0x3e, 0x80, 0x7b, 0x51, 0xf0, 0x79, 0x72, 0xf1, 0x31, 0x3a, 0x0f, 0x4e, 0xc6, 0xa3,
	0x71, 0x70, 0x6a, 0x1c, 0xd0, 0xff, 0x40, 0xf9, 0x30, 0x7c, 0x1f, 0x18, 0x84, 0x02, 0xa8, 0xa3,
	0x80, 0x9f, 0xa5, 0xc1, 0x4f, 0x09, 0x7a, 0x75, 0x8b, 0x08, 0x8b, 0xeb, 0x74, 0x8a, 0x74, 0x04,
	0xba, 0xb0, 0x3c, 0xfa, 0x44, 0xa4, 0xdb, 0xde, 0xac, 0xf5, 0x50, 0xf4, 0x37, 0x69, 0xef, 0x00,
	0x6e, 0x2e, 0x0e, 0x3d, 0x16, 0x83, 0x84, 0x2b, 0xb5, 0xaf, 0xc2, 0x08, 0x74, 0x61, 0x13, 0x6d,
	0x25, 0xed, 0x35, 0xed, 0xab, 0x73, 0x06, 0xba, 0x00, 0xb3, 0x5d, 0xa7, 0x4d, 0xda, 0x7a, 0xf4,
	0xd7, 0xa7, 0x11, 0x94, 0x7f, 0x86, 0x4b, 0x95, 0xdb, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x01, 0xa3, 0x92, 0xf8, 0x90, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateProfileReq, opts ...grpc.CallOption) (*Profile, error)
	GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*Profile, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*Profile, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) CreateProfile(ctx context.Context, in *CreateProfileReq, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/DeleteProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	CreateProfile(context.Context, *CreateProfileReq) (*Profile, error)
	GetProfile(context.Context, *GetProfileReq) (*Profile, error)
	UpdateProfile(context.Context, *UpdateProfileReq) (*Profile, error)
	DeleteProfile(context.Context, *DeleteProfileReq) (*empty.Empty, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) CreateProfile(ctx context.Context, req *CreateProfileReq) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (*UnimplementedProfileServiceServer) GetProfile(ctx context.Context, req *GetProfileReq) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedProfileServiceServer) UpdateProfile(ctx context.Context, req *UpdateProfileReq) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedProfileServiceServer) DeleteProfile(ctx context.Context, req *DeleteProfileReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfile(ctx, req.(*CreateProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfile(ctx, req.(*GetProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, req.(*UpdateProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/DeleteProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteProfile(ctx, req.(*DeleteProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile_grpc.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileService_CreateProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ProfileService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ProfileService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ProfileService_DeleteProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
