// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserWithToken struct {
	User                 *User      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	TokenPair            *TokenPair `protobuf:"bytes,2,opt,name=tokenPair,proto3" json:"tokenPair,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserWithToken) Reset()         { *m = UserWithToken{} }
func (m *UserWithToken) String() string { return proto.CompactTextString(m) }
func (*UserWithToken) ProtoMessage()    {}
func (*UserWithToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserWithToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithToken.Unmarshal(m, b)
}
func (m *UserWithToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithToken.Marshal(b, m, deterministic)
}
func (m *UserWithToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithToken.Merge(m, src)
}
func (m *UserWithToken) XXX_Size() int {
	return xxx_messageInfo_UserWithToken.Size(m)
}
func (m *UserWithToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithToken proto.InternalMessageInfo

func (m *UserWithToken) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserWithToken) GetTokenPair() *TokenPair {
	if m != nil {
		return m.TokenPair
	}
	return nil
}

type TokenPair struct {
	IdToken              string   `protobuf:"bytes,1,opt,name=idToken,proto3" json:"idToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenPair) Reset()         { *m = TokenPair{} }
func (m *TokenPair) String() string { return proto.CompactTextString(m) }
func (*TokenPair) ProtoMessage()    {}
func (*TokenPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *TokenPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenPair.Unmarshal(m, b)
}
func (m *TokenPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenPair.Marshal(b, m, deterministic)
}
func (m *TokenPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPair.Merge(m, src)
}
func (m *TokenPair) XXX_Size() int {
	return xxx_messageInfo_TokenPair.Size(m)
}
func (m *TokenPair) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPair.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPair proto.InternalMessageInfo

func (m *TokenPair) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *TokenPair) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user_grpc.User")
	proto.RegisterType((*CreateReq)(nil), "user_grpc.CreateReq")
	proto.RegisterType((*UpdateReq)(nil), "user_grpc.UpdateReq")
	proto.RegisterType((*LoginReq)(nil), "user_grpc.LoginReq")
	proto.RegisterType((*ID)(nil), "user_grpc.ID")
	proto.RegisterType((*UserWithToken)(nil), "user_grpc.UserWithToken")
	proto.RegisterType((*TokenPair)(nil), "user_grpc.TokenPair")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xb5, 0x8e, 0x93, 0xd4, 0x93, 0xb7, 0x2f, 0x68, 0x5b, 0x14, 0xcb, 0x52, 0x20, 0x32,
	0x1c, 0x82, 0x44, 0x1c, 0xe4, 0x4a, 0xa1, 0x1c, 0x6b, 0x22, 0xa1, 0x48, 0x1c, 0x90, 0x49, 0x41,
	0x02, 0xf1, 0x67, 0x1b, 0x4f, 0x53, 0x0b, 0x27, 0x36, 0xeb, 0x4d, 0x2b, 0x40, 0x1c, 0xf8, 0x06,
	0x9c, 0xf9, 0x1c, 0x7c, 0xba, 0x9c, 0x90, 0x77, 0x6d, 0xc7, 0x4d, 0x55, 0xa2, 0xde, 0x3c, 0xbb,
	0xcf, 0xec, 0xfc, 0x9e, 0xd1, 0x63, 0x80, 0x65, 0x8a, 0xdc, 0x49, 0x78, 0x2c, 0x62, 0x6a, 0x64,
	0xdf, 0x1f, 0x67, 0x3c, 0x99, 0x5a, 0xed, 0x73, 0x16, 0x85, 0x01, 0x13, 0x38, 0x28, 0x3e, 0x94,
	0xc6, 0xba, 0x37, 0x8b, 0xe3, 0x59, 0x84, 0x03, 0x59, 0x9d, 0x2c, 0x4f, 0x07, 0x22, 0x9c, 0x63,
	0x2a, 0xd8, 0x3c, 0xc9, 0x05, 0x77, 0x37, 0x05, 0x17, 0x9c, 0x25, 0x09, 0xf2, 0x54, 0xdd, 0xdb,
	0x7f, 0x08, 0xe8, 0xc7, 0x29, 0x72, 0xfa, 0x3f, 0x68, 0x61, 0x60, 0x92, 0x2e, 0xe9, 0xd5, 0x7c,
	0x2d, 0x0c, 0x28, 0x05, 0x7d, 0xc1, 0xe6, 0x68, 0x6a, 0x5d, 0xd2, 0x33, 0x7c, 0xf9, 0x4d, 0xf7,
	0xa1, 0x8e, 0x73, 0x16, 0x46, 0x66, 0x4d, 0x1e, 0xaa, 0x82, 0x1e, 0x82, 0x31, 0xe5, 0xc8, 0x04,
	0x06, 0x47, 0xc2, 0xd4, 0xbb, 0xa4, 0xd7, 0x72, 0x2d, 0x47, 0x8d, 0x75, 0x8a, 0xb1, 0xce, 0xa4,
	0xe0, 0xf2, 0xd7, 0xe2, 0xac, 0x73, 0x99, 0x04, 0x79, 0x67, 0x7d, 0x7b, 0x67, 0x29, 0xb6, 0x7f,
	0x12, 0x30, 0x9e, 0xc9, 0x77, 0x7c, 0xfc, 0x42, 0x3b, 0x39, 0x6b, 0x46, 0x6f, 0x78, 0xc6, 0xca,
	0x6b, 0x70, 0xfd, 0x36, 0x31, 0x21, 0xc7, 0xee, 0x14, 0xd8, 0xd2, 0x8b, 0xd7, 0x5c, 0x79, 0x3a,
	0xd7, 0x3e, 0x91, 0x82, 0x7f, 0x08, 0x3b, 0x09, 0x4b, 0xd3, 0x8b, 0x98, 0x07, 0xca, 0x98, 0x67,
	0xad, 0xbc, 0x36, 0xbf, 0xe3, 0xee, 0x7d, 0x78, 0x77, 0xd4, 0x7f, 0xcb, 0xfa, 0xdf, 0x1e, 0xf7,
	0x9f, 0xbe, 0xff, 0x3e, 0x7c, 0xf4, 0xc4, 0xfd, 0xf1, 0xc0, 0x2f, 0xb5, 0xf6, 0x6f, 0x02, 0xc6,
	0xb1, 0x24, 0xca, 0x18, 0xda, 0xeb, 0xfd, 0xc9, 0x09, 0xb6, 0xd6, 0x23, 0x72, 0x91, 0x9d, 0xea,
	0x22, 0xff, 0x01, 0x57, 0xdb, 0x0a, 0xa7, 0xdf, 0x00, 0x8e, 0xc1, 0xce, 0x8b, 0x78, 0x16, 0x2e,
	0xd4, 0x7a, 0xf2, 0x11, 0x64, 0xeb, 0x08, 0xed, 0x06, 0x23, 0x3a, 0xa0, 0x8d, 0x47, 0xd7, 0xfa,
	0xb6, 0xcf, 0x60, 0x37, 0x0b, 0xd6, 0x9b, 0x50, 0x9c, 0x4d, 0xe2, 0xcf, 0xb8, 0xa0, 0xf7, 0x41,
	0xcf, 0x12, 0x2d, 0xb5, 0x2d, 0xf7, 0x96, 0x53, 0xc6, 0xdb, 0xc9, 0x74, 0xbe, 0xbc, 0xa4, 0x2e,
	0x18, 0x22, 0x53, 0xbf, 0x64, 0x21, 0x97, 0x34, 0x2d, 0x77, 0xbf, 0xa2, 0x9c, 0x14, 0x77, 0xfe,
	0x5a, 0x66, 0x8f, 0xc1, 0x28, 0xcf, 0xa9, 0x09, 0xcd, 0x30, 0x90, 0xa5, 0xb2, 0xeb, 0x17, 0x25,
	0xb5, 0xe1, 0x3f, 0x8e, 0xa7, 0x1c, 0x53, 0xc5, 0x93, 0x27, 0xfb, 0xd2, 0x99, 0xfb, 0x4b, 0x83,
	0x56, 0x46, 0xf3, 0x0a, 0xf9, 0x79, 0x38, 0x45, 0x7a, 0x08, 0x0d, 0x15, 0x33, 0x5a, 0xa5, 0x28,
	0x93, 0x67, 0x99, 0x1b, 0x2e, 0xd6, 0x6e, 0x1f, 0x42, 0xf3, 0x39, 0x0a, 0xef, 0xeb, 0x78, 0x44,
	0x77, 0x2b, 0xa2, 0xf1, 0xc8, 0xda, 0x74, 0x4e, 0x07, 0xd0, 0x50, 0x39, 0xba, 0x34, 0xa4, 0x8c,
	0xd6, 0xd5, 0x86, 0x03, 0x68, 0x8c, 0x30, 0x42, 0x81, 0x9b, 0x4f, 0x5f, 0xfd, 0x7b, 0xbc, 0x38,
	0x8e, 0x5e, 0xb3, 0x68, 0x89, 0x74, 0x08, 0x75, 0x99, 0x08, 0xba, 0x57, 0xe9, 0x29, 0x32, 0x72,
	0xbd, 0x91, 0x93, 0x86, 0x7c, 0xeb, 0xe0, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x93, 0x1d,
	0x1e, 0x9b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*UserWithToken, error)
	GetByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*User, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*UserWithToken, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*UserWithToken, error) {
	out := new(UserWithToken)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*UserWithToken, error) {
	out := new(UserWithToken)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateReq) (*UserWithToken, error)
	GetByID(context.Context, *ID) (*User, error)
	Update(context.Context, *UpdateReq) (*User, error)
	Delete(context.Context, *ID) (*wrappers.BoolValue, error)
	Login(context.Context, *LoginReq) (*UserWithToken, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateReq) (*UserWithToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) GetByID(ctx context.Context, req *ID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UpdateReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *ID) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginReq) (*UserWithToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _UserService_GetByID_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
